spring:
  datasource:
    url: jdbc:h2:mem:compassdb
    driver-class-name: org.h2.Driver
    username: sa
    password: compassuol
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
